[package]
name = "ds-and-alg"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "*"
tokio = { version = "*", features = ["full"] }
sea-orm = { version = "0.12", features = [
    "sqlx-mysql",
    "runtime-tokio-rustls",
    "macros",
] }
